apiVersion: apps/v1
kind: Deployment
metadata:
  name: apartment-app-deployment
  namespace: apartment-app
  labels:
    app: apartment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apartment-app
  template:
    metadata:
      labels:
        app: apartment-app
    spec:
      containers:
      - name: apartment-app
        image: ghcr.io/kiranmsteam/apartment-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: PORT
          value: "8080"
        - name: GOOGLE_SHEETS_CREDENTIALS_FILE
          value: "/app/hitech-citadel-965501da1a49.json"
        - name: GOOGLE_SHEET_BALANCE_ID
          value: "1Mi-75vRlh8NMTrtrZoe9ionJL3LLFPyULzVtWRgHohg"
        - name: GOOGLE_SHEET_CRDR_ID
          value: "1Gm8MZhpuaJHG7BGbxsm0uf2eNFSy-hLR4wTai67uRyY"
        volumeMounts:
        - name: gcp-creds
          mountPath: /app/hitech-citadel-965501da1a49.json
          subPath: hitech-citadel-965501da1a49.json
          readOnly: true
      volumes:
      - name: gcp-creds
        secret:
          secretName: gcp-credentials
