apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apartment-app-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kiranmsteam/Appartment-ArgoCD.git'
    targetRevision: HEAD
    path: helm-chart/apartment-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: "latest"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apartment-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
