# Default values for apartment-app Helm chart.

replicaCount: 2

image:
  repository: ghcr.io/kiranmsteam/apartment-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 8080
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  port: "8080"
  envName: "development"
  googleSheetsCredentialsFile: "gcp-credentials.json"
  googleSheetBalanceId: "YOUR_BALANCE_SHEET_ID"
  googleSheetContributionsId: "YOUR_CONTRIBUTIONS_SHEET_ID"
  googleSheetCrdrId: "YOUR_CRDR_SHEET_ID"
  googleSheetUsersId: "YOUR_USERS_SHEET_ID"
